"""
Jarvis V2 - Research Controller
================================
Automated research mode that gathers information on any topic.

Features:
- Web search and content extraction
- Wikipedia integration
- Automatic file organization
- Research reports generation
- Source citation
"""

from __future__ import annotations

import json
import os
import re
import webbrowser
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

try:
    import requests
    from bs4 import BeautifulSoup
    import wikipedia
except ImportError:
    requests = None
    BeautifulSoup = None
    wikipedia = None


class ResearchController:
    """
    Research mode controller for Jarvis V2.

    Gathers information on topics and organizes it into structured folders.
    """

    def __init__(self, config: Any = None):
        self.config = config
        self.research_dir = Path("research")
        self.research_dir.mkdir(exist_ok=True)

        self.current_topic = None
        self.current_research_dir = None
        self.sources = []
        self.notes = []

    def start_research(self, topic: str) -> dict[str, Any]:
        """
        Start researching a topic.

        Args:
            topic: The topic to research

        Returns:
            Dictionary with research status and initial findings
        """
        # Clean topic for folder name
        clean_topic = self._clean_filename(topic)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        folder_name = f"{clean_topic}_{timestamp}"

        self.current_topic = topic
        self.current_research_dir = self.research_dir / folder_name
        self.current_research_dir.mkdir(parents=True, exist_ok=True)

        # Create subfolders
        (self.current_research_dir / "sources").mkdir(exist_ok=True)
        (self.current_research_dir / "notes").mkdir(exist_ok=True)
        (self.current_research_dir / "images").mkdir(exist_ok=True)

        # Initialize research
        self.sources = []
        self.notes = []

        # Create research log
        self._create_research_log(topic)

        # Gather initial information
        results = self._gather_initial_info(topic)

        return {
            "success": True,
            "topic": topic,
            "folder": str(self.current_research_dir),
            "initial_findings": results,
            "message": f"Research started on '{topic}'. Folder created at: {self.current_research_dir}"
        }

    def _clean_filename(self, name: str) -> str:
        """Clean a string for use as filename."""
        # Remove special characters
        clean = re.sub(r'[^\w\s-]', '', name)
        # Replace spaces with underscores
        clean = re.sub(r'[\s]+', '_', clean)
        # Limit length
        return clean[:50]

    def _create_research_log(self, topic: str):
        """Create the main research log file."""
        log_content = f"""# Research Log: {topic}

**Started:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** In Progress

---

## Overview

This document contains research findings on: **{topic}**

---

## Key Findings

(To be updated as research progresses)

---

## Sources

(Sources will be added automatically)

---

## Notes

(Additional notes and observations)

---

*Generated by Jarvis V2 Research Mode*
"""
        log_file = self.current_research_dir / "research_log.md"
        log_file.write_text(log_content, encoding="utf-8")

    def _gather_initial_info(self, topic: str) -> dict[str, Any]:
        """Gather initial information about the topic."""
        results = {
            "wikipedia": None,
            "web_search": [],
            "quick_facts": []
        }

        # Wikipedia summary
        if wikipedia:
            try:
                summary = wikipedia.summary(topic, sentences=5)
                results["wikipedia"] = {
                    "summary": summary,
                    "url": wikipedia.page(topic).url
                }

                # Save Wikipedia info
                wiki_file = self.current_research_dir / "sources" / "wikipedia.md"
                wiki_content = f"""# Wikipedia: {topic}

## Summary

{summary}

## Source

{wikipedia.page(topic).url}

---
*Retrieved: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
                wiki_file.write_text(wiki_content, encoding="utf-8")
                self.sources.append({"type": "wikipedia", "url": wikipedia.page(topic).url})

            except Exception as e:
                results["wikipedia"] = {"error": str(e)}

        # Web search (using requests if available)
        if requests:
            try:
                # Use DuckDuckGo instant answer API
                search_url = f"https://api.duckduckgo.com/?q={topic}&format=json"
                response = requests.get(search_url, timeout=10)

                if response.status_code == 200:
                    data = response.json()

                    # Abstract
                    if data.get("Abstract"):
                        results["web_search"].append({
                            "source": data.get("AbstractSource", "DuckDuckGo"),
                            "text": data["Abstract"],
                            "url": data.get("AbstractURL", "")
                        })

                    # Related topics
                    for topic_item in data.get("RelatedTopics", [])[:5]:
                        if isinstance(topic_item, dict) and topic_item.get("Text"):
                            results["web_search"].append({
                                "source": "DuckDuckGo",
                                "text": topic_item["Text"],
                                "url": topic_item.get("FirstURL", "")
                            })

                    # Save search results
                    search_file = self.current_research_dir / "sources" / "web_search.md"
                    search_content = f"# Web Search Results: {topic}\n\n"
                    for i, result in enumerate(results["web_search"], 1):
                        search_content += f"## Result {i}\n\n"
                        search_content += f"**Source:** {result['source']}\n\n"
                        search_content += f"{result['text']}\n\n"
                        if result['url']:
                            search_content += f"**URL:** {result['url']}\n\n"
                        search_content += "---\n\n"

                    search_file.write_text(search_content, encoding="utf-8")

            except Exception as e:
                results["web_search"].append({"error": str(e)})

        # Generate quick facts
        results["quick_facts"] = self._generate_quick_facts(topic, results)

        # Save quick facts
        facts_file = self.current_research_dir / "quick_facts.md"
        facts_content = f"# Quick Facts: {topic}\n\n"
        for fact in results["quick_facts"]:
            facts_content += f"- {fact}\n"
        facts_file.write_text(facts_content, encoding="utf-8")

        return results

    def _generate_quick_facts(self, topic: str, data: dict) -> list[str]:
        """Generate quick facts from gathered data."""
        facts = []

        if data.get("wikipedia") and data["wikipedia"].get("summary"):
            # Extract first sentence as fact
            summary = data["wikipedia"]["summary"]
            first_sentence = summary.split(".")[0] + "."
            facts.append(first_sentence)

        if data.get("web_search"):
            for result in data["web_search"][:3]:
                if result.get("text"):
                    # Take first 100 chars as fact
                    fact = result["text"][:100] + "..." if len(result["text"]) > 100 else result["text"]
                    facts.append(fact)

        if not facts:
            facts.append(f"Research topic: {topic}")
            facts.append("Further investigation recommended")

        return facts

    def add_note(self, note: str) -> dict[str, Any]:
        """Add a note to the current research."""
        if not self.current_research_dir:
            return {"success": False, "message": "No active research session"}

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        note_entry = f"[{timestamp}] {note}"

        self.notes.append(note_entry)

        # Save to notes file
        notes_file = self.current_research_dir / "notes" / "research_notes.md"
        if notes_file.exists():
            content = notes_file.read_text(encoding="utf-8")
        else:
            content = f"# Research Notes: {self.current_topic}\n\n"

        content += f"\n- {note_entry}"
        notes_file.write_text(content, encoding="utf-8")

        return {"success": True, "message": "Note added"}

    def search_web(self, query: str) -> dict[str, Any]:
        """Perform a web search and save results."""
        if not self.current_research_dir:
            return {"success": False, "message": "No active research session"}

        results = []

        if requests:
            try:
                # Use DuckDuckGo
                search_url = f"https://api.duckduckgo.com/?q={query}&format=json"
                response = requests.get(search_url, timeout=10)

                if response.status_code == 200:
                    data = response.json()

                    if data.get("Abstract"):
                        results.append({
                            "source": data.get("AbstractSource", "DuckDuckGo"),
                            "text": data["Abstract"],
                            "url": data.get("AbstractURL", "")
                        })

                    for topic in data.get("RelatedTopics", [])[:5]:
                        if isinstance(topic, dict) and topic.get("Text"):
                            results.append({
                                "source": "DuckDuckGo",
                                "text": topic["Text"],
                                "url": topic.get("FirstURL", "")
                            })

            except Exception as e:
                results.append({"error": str(e)})

        # Save results
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        search_file = self.current_research_dir / "sources" / f"search_{timestamp}.md"

        content = f"# Search: {query}\n\n**Timestamp:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        for i, result in enumerate(results, 1):
            content += f"## Result {i}\n\n"
            content += f"**Source:** {result.get('source', 'Unknown')}\n\n"
            content += f"{result.get('text', 'No text')}\n\n"
            if result.get('url'):
                content += f"**URL:** {result['url']}\n\n"
            content += "---\n\n"

        search_file.write_text(content, encoding="utf-8")

        return {
            "success": True,
            "results": results,
            "saved_to": str(search_file)
        }

    def open_website(self, url: str) -> dict[str, Any]:
        """Open a website and save it as a source."""
        if not self.current_research_dir:
            return {"success": False, "message": "No active research session"}

        # Add to sources
        self.sources.append({"type": "web", "url": url, "added": datetime.now().isoformat()})

        # Save source
        sources_file = self.current_research_dir / "sources" / "sources_list.json"
        if sources_file.exists():
            sources = json.loads(sources_file.read_text(encoding="utf-8"))
        else:
            sources = []

        sources.append({
            "url": url,
            "added": datetime.now().isoformat(),
            "type": "web"
        })

        sources_file.write_text(json.dumps(sources, indent=2), encoding="utf-8")

        # Open in browser
        webbrowser.open(url)

        return {"success": True, "message": f"Opened: {url}"}

    def generate_report(self) -> dict[str, Any]:
        """Generate a comprehensive research report."""
        if not self.current_research_dir:
            return {"success": False, "message": "No active research session"}

        # Read all gathered information
        report_content = f"""# Research Report: {self.current_topic}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** Complete

---

## Executive Summary

This report contains comprehensive research findings on: **{self.current_topic}**

---

## Key Findings

"""

        # Add quick facts
        facts_file = self.current_research_dir / "quick_facts.md"
        if facts_file.exists():
            report_content += "### Quick Facts\n\n"
            report_content += facts_file.read_text(encoding="utf-8").replace("# Quick Facts:", "") + "\n\n"

        # Add Wikipedia info
        wiki_file = self.current_research_dir / "sources" / "wikipedia.md"
        if wiki_file.exists():
            report_content += "### Background Information\n\n"
            report_content += wiki_file.read_text(encoding="utf-8").replace("# Wikipedia:", "") + "\n\n"

        # Add notes
        notes_file = self.current_research_dir / "notes" / "research_notes.md"
        if notes_file.exists():
            report_content += "### Research Notes\n\n"
            report_content += notes_file.read_text(encoding="utf-8").replace(f"# Research Notes: {self.current_topic}", "") + "\n\n"

        # Add sources
        report_content += "## Sources\n\n"
        sources_file = self.current_research_dir / "sources" / "sources_list.json"
        if sources_file.exists():
            sources = json.loads(sources_file.read_text(encoding="utf-8"))
            for i, source in enumerate(sources, 1):
                report_content += f"{i}. {source.get('url', 'Unknown')}\n"
        else:
            report_content += "- Wikipedia\n"
            report_content += "- DuckDuckGo Search\n"

        report_content += f"""

---

## Research Methodology

1. Initial topic exploration using Wikipedia
2. Web search for additional information
3. Source verification and citation
4. Note-taking and organization
5. Report generation

---

## Conclusion

This research provides a comprehensive overview of **{self.current_topic}**.
For more detailed information, please refer to the individual source files in the `sources/` folder.

---

*Generated by Jarvis V2 Research Mode*
"""

        # Save report
        report_file = self.current_research_dir / "RESEARCH_REPORT.md"
        report_file.write_text(report_content, encoding="utf-8")

        # Update research log
        log_file = self.current_research_dir / "research_log.md"
        if log_file.exists():
            log_content = log_file.read_text(encoding="utf-8")
            log_content = log_content.replace("**Status:** In Progress", "**Status:** Complete")
            log_content += f"\n\n**Completed:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            log_file.write_text(log_content, encoding="utf-8")

        return {
            "success": True,
            "report_path": str(report_file),
            "message": f"Research report generated: {report_file}"
        }

    def get_status(self) -> dict[str, Any]:
        """Get current research status."""
        if not self.current_research_dir:
            return {
                "active": False,
                "message": "No active research session"
            }

        # Count files
        sources_count = len(list((self.current_research_dir / "sources").glob("*")))
        notes_count = len(self.notes)

        return {
            "active": True,
            "topic": self.current_topic,
            "folder": str(self.current_research_dir),
            "sources_count": sources_count,
            "notes_count": notes_count,
            "started": self.current_research_dir.name.split("_")[-1] if "_" in self.current_research_dir.name else "Unknown"
        }

    def end_research(self) -> dict[str, Any]:
        """End the current research session."""
        if not self.current_research_dir:
            return {"success": False, "message": "No active research session"}

        # Generate final report
        report_result = self.generate_report()

        topic = self.current_topic
        folder = str(self.current_research_dir)

        # Reset state
        self.current_topic = None
        self.current_research_dir = None
        self.sources = []
        self.notes = []

        return {
            "success": True,
            "message": f"Research completed on '{topic}'. Report saved to: {folder}",
            "report": report_result
        }

    def list_research(self) -> list[dict[str, Any]]:
        """List all research sessions."""
        research_list = []

        if self.research_dir.exists():
            for folder in sorted(self.research_dir.iterdir(), reverse=True):
                if folder.is_dir():
                    # Extract topic from folder name
                    parts = folder.name.rsplit("_", 1)
                    topic = parts[0] if len(parts) > 1 else folder.name
                    timestamp = parts[1] if len(parts) > 1 else "Unknown"

                    # Check if report exists
                    report_exists = (folder / "RESEARCH_REPORT.md").exists()

                    research_list.append({
                        "topic": topic.replace("_", " "),
                        "folder": str(folder),
                        "timestamp": timestamp,
                        "has_report": report_exists
                    })

        return research_list


def get_research_controller(config: Any = None) -> ResearchController:
    """Get or create the global ResearchController instance."""
    if not hasattr(get_research_controller, "_instance"):
        get_research_controller._instance = ResearchController(config)
    return get_research_controller._instance
